name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  lint_and_build:
    name: 'Lint and Build'
    runs-on: ubuntu-latest
    outputs:
      build_success: ${{ steps.build.outcome }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        id: lint
        run: npm run lint

      - name: Build project
        id: build
        run: npm run build
        env:
          NEXT_PUBLIC_ODPT_API_KEY: ${{ secrets.NEXT_PUBLIC_ODPT_API_KEY }}
          NEXT_PUBLIC_USE_MOCK_DATA: ${{ secrets.NEXT_PUBLIC_USE_MOCK_DATA }}

  deploy_production:
    name: 'Deploy to Vercel Production'
    needs: lint_and_build
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}